import { DynamicTool } from "@langchain/core/tools";
import { executeQuery } from "@/lib/postgres";
import { ChatGroq } from "@langchain/groq";

export const UserQuery = new DynamicTool({
  name: "user_query",
  description: `You are an AI agent that helps generate and execute SQL queries for PostgreSQL based on natural language prompts. The database contains user-related tables with a comprehensive relational schema. Use the schema below to understand the structure and relationships when writing queries.

Database Schema:

1. users:
- user_id (INT, PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY)
- username (VARCHAR, UNIQUE)
- email (VARCHAR, UNIQUE)
- password_hash (VARCHAR)
- created_at (TIMESTAMP)
- updated_at (TIMESTAMP)

2. UserProfiles:
- profile_id (INT, PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY)
- user_id (INT, FOREIGN KEY to users.user_id)
- full_name (VARCHAR)
- bio (TEXT)
- profile_picture_url (TEXT)
- location (VARCHAR)
- birthdate (DATE)
- city_id (INT, FOREIGN KEY to Cities.city_id)

3. Cities:
- city_id (INT, PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY)
- city_name (VARCHAR)
- state (VARCHAR)
- country (VARCHAR)
- postal_code (VARCHAR)
- created_at (TIMESTAMP)

4. UserRoles:
- role_id (INT, PRIMARY KEY, GENERATED BY DEFAULT AS IDENTITY)
- role_name (VARCHAR, UNIQUE)

5. UserRoleMappings:
- user_id (INT, FOREIGN KEY to users.user_id)
- role_id (INT, FOREIGN KEY to UserRoles.role_id)
- PRIMARY KEY (user_id, role_id)

Instructions:
- Input will be a natural language query about users and their related data.
- Generate valid PostgreSQL SQL queries using JOINs when needed to access related tables.
- Execute the query and return only the query result (do not explain the query).
- You may query across all defined tables and their relationships.
- Do not include the password_hash column in any SELECT clause.
- Always use table aliases in SELECT and JOIN clauses.
- Use LIMIT 50 to restrict result size in SELECT queries.
- Do not create or drop tables. You may use SELECT, UPDATE, or DELETE only.

Example Prompts:
- "Show all users from Lahore" → JOIN users, UserProfiles, and Cities
- "Find users with admin role" → JOIN users, UserRoleMappings, and UserRoles
- "Show user profiles with their cities" → JOIN UserProfiles with Cities`,


  func: async (input: string) => {
    try {
      console.log("UserQuery tool called with input:", input);
      
      const model = new ChatGroq({
        apiKey: process.env.GROQ_API_KEY!,
        model: "llama3-70b-8192",
      });

     const sqlPrompt = `
You are a SQL query generator. Given a natural language query about users, generate a valid PostgreSQL SQL query.
Query intent: ${input}
Database schema:
1. users: user_id (INT PK), username (VARCHAR), email (VARCHAR), password_hash (VARCHAR), created_at, updated_at
2. UserProfiles: profile_id (INT PK), user_id (FK), full_name (VARCHAR), bio (TEXT), profile_picture_url (TEXT), location (VARCHAR), birthdate (DATE), city_id (FK)
3. Cities: city_id (INT PK), city_name (VARCHAR), state (VARCHAR), country (VARCHAR), postal_code (VARCHAR), created_at
4. UserRoles: role_id (INT PK), role_name (VARCHAR)
5. UserRoleMappings: user_id (FK), role_id (FK)

Rules:
1. Only return the SQL query, no explanations or extra text
2. Use proper PostgreSQL syntax
3. You may generate SELECT, UPDATE, or DELETE queries, but DO NOT create or drop tables
4. All SELECT queries must include LIMIT 50
5. Never include the password_hash column in SELECT clauses
6. Use table aliases for SELECT and JOIN clauses only (e.g., SELECT u.username FROM users u)
7. Do NOT use aliases in UPDATE or DELETE statements — always reference full table names (e.g., UPDATE users SET ...)
8. Use only the exact table and column names provided — do not change or rename them
9. Only use standard ASCII characters in queries — no special characters, quotes, or markdown
10. The SQL query must be valid PostgreSQL and executable as-is, with no formatting, backticks, or markdown
11. If the query does not return any results, return a message indicating that no results were found while reflecting the original parameters or filters used in the query.
User query: "${input}"

SQL query:`;

      const response = await model.invoke([
        { role: "user", content: sqlPrompt }
      ]);

      let sqlQuery = response.content.toString()
        .replace(/[`\n\r\t]/g, ' ')
        .replace(/[^\x00-\x7F]+/g, '') 
        .replace(/\s+/g, ' ') 
        .trim();
      

      const results = await executeQuery(sqlQuery);
      
      console.log(`Query executed successfully, found ${Array.isArray(results) ? results.length : 0} results`);

      if (Array.isArray(results) && results.length > 0) {
        const formattedResults = results.map((row: any, index: number) => {
          const { password, password_hash, ...safeRow } = row; 
          return `${index + 1}. ${Object.entries(safeRow).map(([key, value]) => `${key}: ${value}`).join(', ')}`;
        }).join('\n');

        return `Found ${results.length} result(s):\n\n${formattedResults}`;
      } else {
        return `No results found for the given query: "${input}". Please check the parameters used.`;
      }

    } catch (error) {
      console.error("Error in UserQuery tool:", error);
      return `Error executing query`;
    }
  }
});

